apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb-service
  replicas: 1 
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        selector: mongodb
    spec:
      serviceAccountName: mongodb-sa
      terminationGracePeriodSeconds: 30
      containers:
      - name: mongodb
        image: mongo
        ports:
        - name: mongo-port
          containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username			
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password      
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      imagePullSecrets:
      - name: regcred
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      storageClassName: sc-hrpc
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 40Gi